# **W_1**

In [ ]:
%%capture
!pip install dlt[duckdb] # Install dlt with all the necessary DuckDB dependencies

In [ ]:
import dlt
import requests
import duckdb

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

for sqrt_value in generator:
    print(sqrt_value)

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)
sum = 0

for value in generator:
    sum += value
    print(sum)

1.0
2.414213562373095
4.146264369941973
6.146264369941973
8.382332347441762

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 13
generator = square_root_generator(limit)
sum = 0

for value in generator:
    print(value)

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0
3.1622776601683795
3.3166247903554
3.4641016151377544
3.605551275463989

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

In [ ]:
def example_people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in example_people_1():
  print(person)


generators_exercise = dlt.pipeline(destination='duckdb', dataset_name='exercise')
exercise_info = generators_exercise.run(example_people_1(),
                                        table_name="exercise")

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}

In [ ]:
def example_people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}

for person in example_people_2():
  print(person)

exercise_info = generators_exercise.run(example_people_2(),
                                        table_name="exercise")

{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}

In [ ]:
print(exercise_info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.21 seconds
1 load package(s) were loaded to destination duckdb and into dataset exercise
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708295895.1326592 is LOADED and contains no failed jobs

In [ ]:
# show outcome
conn = duckdb.connect(f"{generators_exercise.pipeline_name}.duckdb")

# let's see the tables
conn.sql(f"SET search_path = '{generators_exercise.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))

# and the data

print("\n\n\n exercise table below:")

exercise = conn.sql("SELECT * FROM exercise").df()
display(exercise)

# As you can see, the same data was loaded in both cases.

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ exercise            │
└─────────────────────┘

 exercise table below:

    id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A  1708295891.0593982  utsWcHSPPZE6hQ       None
1    2  Person_2   27  City_A  1708295891.0593982  wWZjhZXo57C72g       None
2    3  Person_3   28  City_A  1708295891.0593982  Z4SqHH2XNITqJg       None
3    4  Person_4   29  City_A  1708295891.0593982  GeNfqlxJ/S0jqA       None
4    5  Person_5   30  City_A  1708295891.0593982  eQIZg9x5R43vGg       None
5    3  Person_3   33  City_B  1708295895.1326592  uP5kkRWpGlqe2w      Job_3
6    4  Person_4   34  City_B  1708295895.1326592  X9+9UtRujvfYBw      Job_4
7    5  Person_5   35  City_B  1708295895.1326592  aMrC6LXkTcUzgQ      Job_5
8    6  Person_6   36  City_B  1708295895.1326592  q0/O8zXS6HYfnQ      Job_6
9    7  Person_7   37  City_B  1708295895.1326592  IoQV6QPiwywMkg      Job_7
10   8  Person_8   38  City_B  1708295895.1326592  kCQuL3AFJODcHA      Job_8

In [ ]:
# show outcome
conn = duckdb.connect(f"{generators_exercise.pipeline_name}.duckdb")

# let's see sum of ages

sum_age_exercise = conn.sql("SELECT SUM(age) FROM exercise").df()
display(sum_age_exercise)

   sum(age)
0     353.0

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

In [ ]:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

sum_age_1 = 0
for person in people_1():
  sum_age_1 += person["Age"]

print("Sum age people 1",sum_age_1)


def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}

sum_age_2 = 0
for person in people_2():
  sum_age_2 += person["Age"]

print("Sum age people 2",sum_age_2)

# define the connection to load to.
# We now use duckdb, but you can switch to Bigquery later
generators_pipeline = dlt.pipeline(destination='duckdb', dataset_name='generators')


# we can load any generator to a table at the pipeline destnation as follows:
info = generators_pipeline.run(people_1(),
										table_name="person",
										write_disposition="replace")

info = generators_pipeline.run(people_2(),
										table_name="person",
										write_disposition="merge",
                    primary_key='ID')

# the outcome metadata is returned by the load and we can inspect it by printing it.
print(info)

Sum age people 1 140
Sum age people 2 213
Pipeline dlt_colab_kernel_launcher load step completed in 0.57 seconds
1 load package(s) were loaded to destination duckdb and into dataset generators
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708294970.6923714 is LOADED and contains no failed jobs

In [ ]:
# show outcome
conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# let's see the tables
conn.sql(f"SET search_path = '{generators_pipeline.dataset_name}'")
print('Loaded tables: ')
display(conn.sql("show tables"))

# and the data

print("\n\n\n person table below:")

person = conn.sql("SELECT * FROM person").df()
display(person)

# As you can see, the same data was loaded in both cases.

Loaded tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ person              │
└─────────────────────┘

 person table below:

   id      name  age    city        _dlt_load_id         _dlt_id occupation
0   1  Person_1   26  City_A  1708294969.8710299  Ifx/aozKsGPvRg       None
1   2  Person_2   27  City_A  1708294969.8710299  anEs6iM3BDYz2g       None
2   5  Person_5   35  City_B  1708294970.6923714  ZZeSTvkpDOV7yg      Job_5
3   7  Person_7   37  City_B  1708294970.6923714  4x9KXkp2w6cvZA      Job_7
4   3  Person_3   33  City_B  1708294970.6923714  ShXkWFeqkE/Pkw      Job_3
5   6  Person_6   36  City_B  1708294970.6923714  JSzJ8472IT0idQ      Job_6
6   8  Person_8   38  City_B  1708294970.6923714  4AIWgocTUqU84Q      Job_8
7   4  Person_4   34  City_B  1708294970.6923714  SyawxweNpup3nA      Job_4

In [ ]:
# show outcome
conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

# let's see sum of ages

sum_age = conn.sql("SELECT SUM(age) FROM person").df()
display(sum_age)

   sum(age)
0     266.0